GRAPH_2D = "graph-2d"
DROPDOWN_2D_DR = "dropdown-2d-dr"
DROPDOWN_2D_CLUSTER = "dropdown-2d-cluster"
GRAPH_2D_OPTIONS = "graph-2d-options"
KMEANS_SLIDER = "kmeans-slider"
MULTI_DROPDOWN_2D_CLUSTER = "multi-dropdown-2d-cluster"
TOGGLE_SWITCH_DIMENSION = "toggle-switch-dimension"
